import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect, useState, useCallback } from "react"
import words from "../utility/words.js"
import WordCloudDiv from "../components/WordCloudDiv.js"
import Loading from "../components/Loading.js"
import { Typography } from "@material-ui/core"

const StatsPage = () => {
    const router = useRouter()
    const [wordFreq, setWordFreq] = useState(null)
    const username = router.query.username
    useEffect(async () => {
        if (!username) {
            return
        }
        let user = await fetch("/api/user", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                username: router.query.username,
            }),
        })
        user = await user.json()
        console.log(user)
        if (user.error) {
            alert("User could not be found!")
        } else {
            var timeline = await fetch("/api/timeline", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    user_id: user.data.id,
                }),
            })
            timeline = await timeline.json()
            var temp = await words(timeline)
            setWordFreq(temp)
        }
    }, [username])
    return (
        <div>
            <Head>
                <title>Twitter Stats</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <a className="username" href={`https://twitter.com/${username}`}>@{username}</a>
            <WordCloudDiv wordFreq={wordFreq}></WordCloudDiv>
        </div>
    )
}

export default StatsPage
