import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect, useState, useCallback } from "react"
import words from "../utility/words.js"
import WordCloudDiv from "../components/WordCloudDiv.js"
import FriendsList from "../components/FriendsList.js"
import GithubLink from "../components/GithubLink.js"

const StatsPage = () => {
    const router = useRouter()
    const [wordFreq, setWordFreq] = useState(null)
    const [friends, setFriends] = useState(null)
    const username = router.query.username

    const redirect_to_user = () => {
        router.push(`https://twitter.com/${username}`)
    }


    useEffect(async () => {
        if (!username) {
            return
        }
        let user = await fetch("/api/user", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                username: router.query.username,
            }),
        })
        user = await user.json()
        console.log(user)
        if (user.error) {
            router.push("/?error=nouser")
        } else {
            var timeline = await fetch("/api/timeline", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    user_id: user.data.id,
                }),
            })
            timeline = await timeline.json()
            const temp = await words(timeline)
            setWordFreq(temp.words)
            setFriends(temp.friends)
        }
    }, [username])
    return (
        <div>
            <Head>
                <title>Twitter Stats</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p className="username" onClick={redirect_to_user}>@{username}</p>
            <hr></hr>
            <p className="stats-headings">The People they tweet at the most often:</p>
            <FriendsList friends={friends}></FriendsList>
            <hr></hr>
            <p className="stats-headings">The Things they tweet about:</p>
            <WordCloudDiv wordFreq={wordFreq}></WordCloudDiv>
            <hr></hr>
            <GithubLink/>
        </div>
    )
}

export default StatsPage
